- hosts: all
  tasks:
    - name: Print distribution family
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: "Include OS-specific packages"
      include_vars: "../vars/{{ ansible_distribution }}.yaml"
      when: ansible_distribution == 'FreeBSD' or ansible_distribution == 'Ubuntu'

    - name: "Include common packages"
      include_vars: "../vars/common-packages.yaml"

    - include_tasks: setup-Ubuntu.yaml
      when: ansible_os_family == 'Ubuntu'

    - include_tasks: setup-FreeBSD.yaml
      when: ansible_os_family == 'FreeBSD'
