- name: "Provisioning Deluge"
  hosts: glitchbrain-prod
  tasks:
    - name: "Install packages"
      community.general.pkgng:
        name:
          - deluge-cli
        state: present

    - name: "Enable deluged service"
      community.general.sysrc:
        name: deluged_enable
        value: "YES"

    - name: "Create deluged user"
      ansible.builtin.user:
        name: "deluge"

    - name: "Set deluged user"
      community.general.sysrc:
        name: deluged_user
        value: "deluge"

    - name: "Create the settings directory"
      ansible.builtin.file:
        path: /home/deluge/.config/deluge
        state: directory
        owner: deluge
        group: deluge
