- name: "Provisioning Deluge"
  hosts: glitchbrain-prod
  tasks:
    - name: "Install packages"
      community.general.pkgng:
        name:
          - qbittorrent-nox
        state: present

    - name: "Enable qbittorrent service"
      community.general.sysrc:
        name: qbittorrent_enable
        value: "YES"

    - name: "Create qbittorrent user"
      ansible.builtin.user:
        name: "torrent"

    - name: "Set qbittorrent user"
      community.general.sysrc:
        name: qbittorrent_user
        value: "torrent"

    - name: "Create the settings directory"
      ansible.builtin.file:
        path: /var/db/qbittorrent
        state: directory
        owner: torrent
        group: torrent
