hosts:
  hosts:
    persephone:
      ansible_host: 163.172.211.189
      http_port: 443
      ansible_port: 4329
    glitchbrain-prod:
      ansible_host: 95.216.241.45
      http_port: 443
      ansible_port: 4022
    flora-prod:
      ansible_host: 95.217.207.190
      ansible_port: 4022
  vars:
    ansible_user: ouranos
    ansible_ssh_private_key_file: ~/.ssh/hecate_ifrit

freebsd:
  hosts:
    glitchbrain-prod:
      ansible_user: root
    flora-prod:
      ansible_user: root
  vars:
    etc_dir: /usr/local/etc

ubuntu:
  hosts:
    persephone:
  vars:
    etc_dir: /etc

web:
  hosts:
    persephone:
    glitchbrain-prod:
